# Generated by Django 5.0.1 on 2024-01-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_amount_yo_use_coupon',
            field=models.PositiveBigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
