# Generated by Django 5.0.1 on 2024-01-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon_required_amount_yo_use_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='required_amount_yo_use_coupon',
            new_name='required_amount_to_use_coupon',
        ),
    ]
